### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by muuuh** [Donohue/testflight_invite#6]
Do you have a fix for the following error?

Error:

    Invite Failed: 'NoneType' object has no attribute 'group'

Position in code:

        urlWebsite = self.urlITCBase % '/WebObjects/iTunesConnect.woa'
        html = self.readHtml(urlWebsite)
        match = re.search('" action="(.*)"', html)

**Comment by Donohue** [comment]
So it looks like the login form has changed and a lot of it is based in JavaScript now. I tried a few things, but it'll require a dive into the iTC JavaScript code, which in my experience takes a lot of time and patience to parse through. If you manage to figure it out feel free to send a PR, but for now this is broken.

**Comment by ninjudd** [comment]
I got pretty close by hitting this JSON endpoint to sign in:
`https://appleid.apple.com/appleauth/auth/signin`
```js
{"accountName": "myUsername",
 "password": "myPassword"}
```
But the cookies set by the server aren't quite right.

The JSON endpoint for adding users is:
`https://itunesconnect.apple.com/WebObjects/iTunesConnect.woa/ra/users/pre/create`
```js
{"testers": [{"emailAddress": {"value": "email@domain.com",
                               "errorKeys": []},
              "firstName": {"value": "Bob"},
              "lastName": {"value": "Smith"},
              "testing": {"value": true},
              "groups": []}]}
```
I think the missing cookie is "myacinfo". It is set when logging in from a browser, but not when hitting `https://appleid.apple.com/appleauth/auth/signin` from a script. I played around with the `X-Apple-Widget-Key` and `X-Apple-I-FD-Client-Info` headers, but couldn't get it to work.

**Comment by Donohue** [comment]
@ninjudd I got about as close as you did with changing the signin endpoint and adjusting the parameters accordingly. However, without the proper cookies I'm getting a `HTTP Error 415: Unsupported Media Type` response.

Since the form is now being submitted via JavaScript, it's likely digging through the iTC JavaScript code will be necessary to determine where the appropriate cookies are being set.

**Comment by ninjudd** [comment]
It's even harder than that, I think. The cookies are being set and used by the server, so they don't appear anywhere in the JavaScript code as far as I can tell.

**Comment by stakemura** [comment]
Is stoprocent/node-itunesconnect#7 of some help?
I'm gonna investigate their commits.

**Comment by Donohue** [comment]
@stakemura yep this looks like the right direction. Holidays are coming up for me so I don't have a ton of time to look into this now but please send a PR if you're able to work out a solution.

**Comment by loretoparisi** [comment]
I confirm the error.
I have not further info of the ones described here:

I changed the login url

```python
html = self.readHtml(urlWebsite)

        urlActionLogin = "https://idmsa.apple.com/appleauth/auth/signin"
        try:
            match = re.search('" action="(.*)"', html)
            if not match is None:
                urlActionLogin = self.urlITCBase % match.group(1)
        except Exception as e:
	        PrintException();
        finally:
            urlActionLogin = "https://idmsa.apple.com/appleauth/auth/signin"
```

The form data

```python
 formData = {'accountName':self.itcLogin,
                                              'password':self.itcPassword,
                                              'rememberMe':'0',
                                              '1.Continue':'0' }
webFormLoginData = urllib.urlencode( formData )
 htmlResponse = self.readHtml(urlActionLogin, webFormLoginData)
```

but of course for the reasons described here no way due to the

```
HTTP Error 415: Unsupported Media Type
```

error, since now the API is basically JavaScript. This is the same API Apple is using on the new iTunes Connect pages since September:

```
Accept:application/json, text/javascript, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:it-IT,it;q=0.8,en-US;q=0.6,en;q=0.4,es;q=0.2,de;q=0.2
Connection:keep-alive
Content-Length:67
Content-Type:application/json
```

**Comment by loretoparisi** [comment]
Of course, there is a well know and complete suite by @KrauseFx written in Ruby that currently works, Spaceship - https://github.com/fastlane/spaceship since it uses a different approach, no web page scraping, but iTunes Connect API reverse engineering, that has several advantages though.

**Comment by KrauseFx** [comment]
Just in case you want to check out the spaceship source code:

If you want to implement this using `spaceship`:
```ruby
# Find an internal tester based on the email address
tester = Spaceship::Tunes::Tester::Internal.find("felix@krausefx.com")

# Same for external testers
tester = Spaceship::Tunes::Tester::External.find("guest@krausefx.com")

# Find all testers that were already added to an application
app.external_testers            # => Array of all external testers for this application


# Creating new external testers
Spaceship::Tunes::Tester::External.create!(email: "github@krausefx.com",
                                      first_name: "Felix",
                                       last_name: "Krause")

# Add all external testers to an application
app.add_all_testers!

# Only add selected testers to an application
# This will add the existing tester (if available) or create a new one
app.add_external_tester!(email: "github@krausefx.com", first_name: "Felix", last_name: "Krause")
```

`tester.rb` https://github.com/fastlane/spaceship/blob/master/lib/spaceship/tunes/tester.rb
`tunes_client.rb` https://github.com/fastlane/spaceship/blob/master/lib/spaceship/tunes/tunes_client.rb

Let me know if you have any questions :smiley:

**Comment by loretoparisi** [comment]
Thanks @KrauseFx! I'm already using Spaceship / fastlane since a while for onboarding, better TestFlight managment, etc, even if I'm more confident with Python.
Yes I have a question, considering the issue here that prevents the @Donohue solution to work.
This Python solution was pretty easy to use in a web server context like using a WSGI Python interface.
How to achieve the same with Spaceship in a non ruby server context, let's say...Python :)?

**Comment by KrauseFx** [comment]
@loretoparisi Sorry, I'm not sure I understand your question.

**Comment by loretoparisi** [comment]
@KrauseFx Sorry. So I used to have a ```WSGI``` multi threaded application behind a http server (like nginix) written in Python 2.7 using ```Flask``` framework web app container like:

```
----------             ----------             -----------------------
| ngnix | <---->  |  Flask | <-----> |  TestFlight API |
---------              ----------             -----------------------
```

Now, assumed that I move to ```fastlane``` as the third component, what will happen? Do I need ```Rails``` behing ```nginx``? There is any way to keep Flask and wrap SpaceShip / Fastlane to be called by Flask (like a socket server, etc)?

LP

**Comment by loretoparisi** [comment]
@Donohue :+1: it works like a charm!

**Comment by stakemura** [comment]
@Donohue I appreciate your great work.
